USERS_CSV = "database/usuarios.csv"
PREFERENCES_CSV = "database/preferencias.csv"
GAMES_CSV = "database/juegos.csv"

USER_ID_COLUMN = "id"
USERNAME_COLUMN = "username"

GAME_ID_COLUMN = "id"
GAME_TITLE_COLUMN = "title"
GAME_DESCRIPTION_COLUMN = "description"
GAME_PLATFORMS_COLUMN = "platforms"

PREFERENCE_USER_ID_COLUMN = "userId"
PREFERENCE_ITEM_ID_COLUMN = "itemId"
PREFERENCE_RANKING_COLUMN = "ranking"

OPEN_WORLD_ACTION_PREFERENCE = "open_world_action_preference"
FPS_PREFERENCE = "fps_preference"
SURVIVAL_PREFERENCE = "survival_preference"
ACTION_RPG_PREFERENCE = "action_rpg_preference"
LINEAR_ACTION_ADVENTURE_PREFERENCE = "linear_action_adventure_preference"

OPEN_WORLD_ACTION_COLUMN = "open_world_action"
FPS_COLUMN = "fps"
SURVIVAL_COLUMN = "survival"
ACTION_RPG_COLUMN = "action_rpg"
LINEAR_ACTION_ADVENTURE_COLUMN = "linear_action_adventure"

USER_ATTRIBUTE_COLUMNS = [
    OPEN_WORLD_ACTION_PREFERENCE,
    FPS_PREFERENCE,
    SURVIVAL_PREFERENCE,
    ACTION_RPG_PREFERENCE,
    LINEAR_ACTION_ADVENTURE_PREFERENCE,
]

USER_COLUMNS = [
    USER_ID_COLUMN,
    USERNAME_COLUMN,
    *USER_ATTRIBUTE_COLUMNS,
]

PREFERENCE_COLUMNS = [
    PREFERENCE_USER_ID_COLUMN,
    PREFERENCE_ITEM_ID_COLUMN,
    PREFERENCE_RANKING_COLUMN,
]

GAME_TO_USER_ATTRIBUTE_MAP = {
    OPEN_WORLD_ACTION_COLUMN: OPEN_WORLD_ACTION_PREFERENCE,
    FPS_COLUMN: FPS_PREFERENCE,
    SURVIVAL_COLUMN: SURVIVAL_PREFERENCE,
    ACTION_RPG_COLUMN: ACTION_RPG_PREFERENCE,
    LINEAR_ACTION_ADVENTURE_COLUMN: LINEAR_ACTION_ADVENTURE_PREFERENCE,
}

PREFERENCE_MIN_VALUE = 0.0
PREFERENCE_MAX_VALUE = 10.0
PREFERENCE_UPDATE_ALPHA = 0.5

RANKING_WEIGHT_MAP = {
    1: -0.25,
    2: -0.10,
    3: 0.0,
    4: 0.20,
    5: 0.10,
}
